services:
  app:
    image: frontend-app
    container_name: frontend-app
    build:
      context: ../frontend_app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - BACKEND=backend
      - AUDIO=audio

  audio:
    image: audio-service
    container_name: audio-service
    build:
      context: ../audio_service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    deploy:
      replicas: 1
    environment:
      - BACKEND=backend

  backend:
    image: backend-service
    container_name: backend-service
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgrespassword@postgres:5432/postgres?schema=public

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=postgres

volumes:
  db-data:
