apiVersion: apps/v1
kind: Deployment
metadata:
  name: audio
  labels:
    app: audio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: audio
  template:
    metadata:
      labels:
        app: audio
    spec:
      containers:
        - name: audio
          image: DOCKERHUB IMAGE AUDIO
          env:
            - name: AUDIO_API_KEY
              value: "your-api-key"
          ports:
            - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: audio
spec:
  ports:
    - port: 3002
  selector:
    app: audio
  type: ClusterIP
