apiVersion: apps/v1
kind: Deployment
metadata:
  name: audio
  labels:
    app: audio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: audio
  template:
    metadata:
      labels:
        app: audio
    spec:
      containers:
        - name: audio
          image: mansnei/cloudcomputing-audio:v1
          env:
            - name: AUDIO_API_KEY
              value: "sk_daa1c1d244f44fbef9559b564bed9753f55bd50933386671"
            - name: NODE_ENV
              value: production
            - name: BACKEND_URL
              value: "http://backend:3001"
          ports:
            - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: audio
spec:
  ports:
    - port: 3002
      targetPort: 3002
  selector:
    app: audio
  type: LoadBalancer
