apiVersion: apps/v1
kind: Deployment
metadata:
  name: audio-deplyoment
  labels:
    app: audio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audio
  template:
    metadata:
      labels:
        app: audio
    spec:
      containers:
      - name: audio
        image: DOCKERHUB IMAGE AUDIO
        ports:
        - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: audio-service
spec:
  selector:
    app: audio
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002