apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: run-migrations
          image: mansnei/cloudcomputing-backend:v1
          command: ["npx", "prisma", "migrate", "deploy"]
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:postgrespassword@postgres:5432/postgres?schema=public"
      containers:
        - name: backend
          image: mansnei/cloudcomputing-backend:v1
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:postgrespassword@postgres:5432/postgres?schema=public"
            - name: NODE_ENV
              value: production
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
    - port: 3001
      targetPort: 3001
  selector:
    app: backend
  type: LoadBalancer
