apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: mansnei/cloudcomputing-frontend:v1
          env:
            - name: REACT_APP_BACKEND_URL
              value: "http://localhost:3001"
            - name: REACT_APP_AUDIO_URL
              value: "http://localhost:3002"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: frontend
  type: LoadBalancer